---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: springcommunity/spring-petclinic-cloud-api-gateway
        name: api-gateway
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 2
            memory: 1Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: JAVA_OPTS
          value: -javaagent:"/mnt/appinsights/applicationinsights-agent-3.4.7.jar"
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
             secretKeyRef:
               name: app-insights-key
               key: instrumentation-key
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/mnt/appinsights"
          name: appinsights
      restartPolicy: Always
      volumes:
        - name: appinsights
          persistentVolumeClaim:
            claimName: appinsights-blob-pvc