apiVersion: v1
kind: PersistentVolume
metadata:
  name: appinsights-blob-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    volumeHandle: appinsights-blob-pv
    volumeAttributes:
      containerName: appinsights-blob
    nodeStageSecretRef:
      name: appinsights-blob-secret
      namespace: spring-petclinic