apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appinsights-blob-pvc
  namespace: spring-petclinic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: appinsights-blob-pv
  storageClassName: azureblob-fuse-premium